name:                tvg
version:             0.1.0.0
github:              "githubuser/tvg"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

#extra-source-files:

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tvg#readme>

dependencies:
- base >= 4.7 && < 5
- process
- language-c == 0.9
- directory
- pretty
- syb
- filepath
- transformers
- text
- strict
- time >= 1.9
- html
- containers
- extra
- blaze-html
- base-unicode-symbols
- regex-tdfa
- language-c-quote
- mainland-pretty
- array
- FloatingHex

executables:
#  tvg-exe:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - tvg

  analyzer-exe:
    main:                Main.hs
    source-dirs:         analyzer
    ghc-options:
#    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

#  covreport-exe:
#    main:                Main.hs
#    source-dirs:         covreport
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - tvg

#  parsecpp-exe:
#    main:                Main.hs
#    source-dirs:         grammar
#    dependencies:
#    - html
#    - parsec

#  prevent-exe:
#    main:                Main.hs
#    source-dirs:         prevent
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
