/**
 * This file was automatically generated by the ForeC++ Framework on Wed Oct 30 13:56:23 2019.
 * 
 * All Rights reserved. Unauthorized copying of this file via any medium is strictly prohibited.
 * Proprietary and confidential.
 */
/* Includes */
#include "target.c.h"
/* Globals */
float __divsf3(float numerator, float denominator);
int main(int argc, const char** argv)
{
	uttc_statistic	statistic[3] = {UTTC_DYNAMIC_STATISTIC, UTTC_DYNAMIC_STATISTIC, UTTC_DYNAMIC_STATISTIC};
	uttc_size_t		statistic_depth = 1;
	{ // Stimuli (19f5b71e)
		float			numerator = 0.f;
		float			denominator = 0.f;
		{ // Test Case (08e36869)
			statistic_depth += 1;
			float			result = __divsf3(numerator, denominator); // Execution (036b394c): representative([numerator].pos_zero) and representative([denominator].pos_zero)
			uttc_verdict	check_verdict = uttc_is_approximatelyfb(result, uttc_nanb(0x400000), uttc_threshold(uttc_fromhexb(0x8.0p-04)/*0.5*/, UTTC_DM_UNITS_IN_LAST_PLACE, true, true)) ? UTTC_VD_PASSING : UTTC_VD_FAILING; // __divsf3.R-1-Check (427a1b62)
			uttc_st_check(statistic, statistic_depth, check_verdict, false, "427a1b62");
			uttc_st_test_case(statistic, statistic_depth -= 1, "08e36869");
		}
	}
	{ // Stimuli (a3938016)
		float			numerator = -2.80259692865e-45f; // sequence-value(9th of 9)
		float			denominator = -2.80259692865e-45f; // sequence-value(9th of 9)
		{ // Test Case (55ec6a14)
			statistic_depth += 1;
			float			result = __divsf3(numerator, denominator); // Execution (312a6a57): representative([denominator].neg_denormal) and representative([numerator].neg_denormal)
			uttc_verdict	check_verdict = uttc_is_approximatelyfb(result, uttc_fromhexb(0x1.0p+00)/*1*/, uttc_threshold(uttc_fromhexb(0x8.0p-04)/*0.5*/, UTTC_DM_UNITS_IN_LAST_PLACE, true, true)) ? UTTC_VD_PASSING : UTTC_VD_FAILING; // __divsf3.R-1-Check (a4c29df6)
			uttc_st_check(statistic, statistic_depth, check_verdict, false, "a4c29df6");
			uttc_st_test_case(statistic, statistic_depth -= 1, "55ec6a14");
		}
	}
	uttc_st_accumulate_global(statistic);
	uttc_print_string("TEST_SUMMARY: ");
	uttc_st_print(statistic[0], true);
	uttc_print_string("\nTEST_VERDICT: ");
	uttc_st_print_verdict(statistic[0]);
	return uttc_exit(uttc_st_is_compliant(statistic[0]) ? 0 : -1);
}
